---
title: "Chapter 07 Risk Management"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Market risk
```{r}
# import data sets
GPSCMonthlyData <- read.csv("Data/GSPC.csv")
IBMMonthlyData <- read.csv("Data/IBM.csv")
DateRange <- GPSCMonthlyData$Date == IBMMonthlyData$Date
GPSCPrice<-GPSCMonthlyData$Close[DateRange]
IBMPrice<-IBMMonthlyData$Close[DateRange]
par(mfrow = c(2, 1))
plot(GPSCPrice)
plot(IBMPrice, type = "o", col="blue")
```
```{r}
GPSCReturns <- ( GPSCPrice[1:(length(GPSCPrice) - 1)] - GPSCPrice[2:length(GPSCPrice)] ) / GPSCPrice[2:length(GPSCPrice)]
IBMReturns <- ( IBMPrice[1:(length(IBMPrice) - 1)] - IBMPrice[2:length(IBMPrice)] ) / IBMPrice[2:length(IBMPrice)]
betafit <- lm(IBMReturns ~ GPSCReturns)
result <- summary(betafit)
beta <- result$coefficients[2,1]
print(beta)
```
## Portfolio risk
```{r}
# get data someshow FB data not complete, so use FB = AAPL for prog to run
GPSCMonthlyData <- read.csv("Data/GSPC.csv")
IBMMonthlyData <- read.csv("Data/IBM.csv")
FBMonthlyData <- read.csv("Data/AAPL.csv")
VMonthlyData <- read.csv("Data/V.csv")
```
```{r}
# data range
DateRange <- GPSCMonthlyData$Date
GPSCPrice<-GPSCMonthlyData$Close[DateRange]
IBMPrice<-IBMMonthlyData$Close[DateRange]
FBPrice<-FBMonthlyData$Close[DateRange]
VPrice<-VMonthlyData$Close[DateRange]

# returns
GPSCReturns <- ( GPSCPrice[1:(length(GPSCPrice) - 1)] - GPSCPrice[2:length(GPSCPrice)] ) / GPSCPrice[2:length(GPSCPrice)]
IBMReturns <- ( IBMPrice[1:(length(IBMPrice) - 1)] - IBMPrice[2:length(IBMPrice)] ) / IBMPrice[2:length(IBMPrice)]
FBReturns <- ( FBPrice[1:(length(FBPrice) - 1)] - FBPrice[2:length(FBPrice)] ) / FBPrice[2:length(FBPrice)]
VReturns <- ( VPrice[1:(length(VPrice) - 1)] - VPrice[2:length(VPrice)] ) / VPrice[2:length(VPrice)]
```
```{r}
# excess return - T-Bills interest rate
EGPSCReturns<- GPSCReturns-.0015
EIBMReturns<- IBMReturns-.0015
EFBReturns<- FBReturns-.0015
EVReturns<- VReturns-.0015
```
```{r}
# find mean and sd for return
MeanSD<-rbind(cbind("GPSC",mean(EGPSCReturns),sd(EGPSCReturns)),cbind("FB",mean(EFBReturns),sd(EFBReturns)),cbind("IBM",mean(EIBMReturns),sd(EIBMReturns)),cbind("V",mean(EVReturns),sd(EVReturns)))
MeanSD
```

```{r}
# find beta
lmIBM<- lm(IBMReturns ~ EGPSCReturns)
summary(lmIBM)
```
Beta of IBM*expected excess return of GPSC


```{r}
# construct matrix tables
returns_avg<-matrix(c(-0.0178634248040147,-0.00211933210558351,-0.0185616855849399),nrow =1)
covariance<-matrix(c(0.001378118,0.000528808,0.004673302,0.000528808,0.000202913,0.001793228,0.004673302,0.001793228,0.015847524),nrow=3)

# find optimal weights
library(tseries)
sol<-portfolio.optim(x=returns_avg,covmat=covariance, shorts=F)
sol$pw
```
## VaR
### Parametric VaR
```{r}
mean = 2
sigma = 4
alpha = .05
Var_parametric <- qnorm(alpha, mean, sigma)
Var_parametric
```
```{r}
# alternative
Var_parametric <- mean + sigma*qnorm(alpha,0,1)
Var_parametric
```
```{r}
# Expected shortfall/ES or CVaR
alpha_z <- qnorm(alpha)
ES_parametric <- mean + sigma*(dnorm(alpha_z)/(1-alpha))
ES_parametric
```
```{r}
# Historical VaR
# obtain data set FB=AAPL for illustration purpose only
library(quantmod)
library(PerformanceAnalytics)
symbollist <-  c("FB", "V","JNJ")
getSymbols(symbollist, from ="2016-01-01", to = "2017-01-01")

FB <- FB[, "FB.Adjusted", drop=F]
V = V[, "V.Adjusted", drop=F]
JNJ <- JNJ[, "JNJ.Adjusted", drop=F]

FB_return <- CalculateReturns(FB, method="log")
V_return <- CalculateReturns(V, method="log")
JNJ_return <- CalculateReturns(JNJ, method="log")

FB_return <- FB_return[-1,]
V_return <- V_return[-1,]
JNJ_return <- JNJ_return[-1,]

FB_V_JNJ_return <- cbind(FB_return,V_return,JNJ_return)
head(FB_V_JNJ_return)
```
```{r}
# estimate individual historical VaR
HVAR<-VaR(FB_V_JNJ_return, p=0.95, method="historical")
HVAR
```
```{r}
# CVAR/ES
HCVAR<-ES(FB_V_JNJ_return, p=0.95, method="historical")
HCVAR
```
```{r}
# equal weight portfolio
VaR(FB_V_JNJ_return, p=0.95,portfolio_method="component")
```
```{r}
# marginal
VaR(FB_V_JNJ_return, p=0.95,portfolio_method="marginal")
```
## Monte Carlo simulation
```{r}
# histogram
Sample_Size<-2000
set.seed(2345)
Z<-rnorm(Sample_Size)
mean<-.20
sigma<-.25
deltat<-.08333
returns<-mean*deltat+sigma*Z*sqrt(deltat)
hist(returns, breaks = 50)
```

```{r}
# results are similar
Mean_new<-mean(returns)*12
Mean_new
std_new<-sd(returns)*(12)^(.5)
std_new
```
```{r}
VaR(returns, p = 0.95, method="historical")
```
## Hedging

## Basel regulation (SACCR package)

## Credit risk
```{r}
# data set
library(caret)
data(GermanCredit)
LRData<-GermanCredit[,1:10]
str(LRData)
```
```{r}
# prepare data 
set.seed(100)
library(caTools)
res = sample.split(LRData$Class, 0.6)
Train_data = subset(LRData, res == TRUE)
Test_data=subset(LRData,res==FALSE)
```
```{r}
# logistic regression
lgfit <- glm(Class ~. , data=Train_data, family="binomial")
summary(lgfit)
```
```{r}
# find best model
lgfit = glm(Class ~Duration+InstallmentRatePercentage+Age, 
            data=Train_data, family="binomial")
summary(lgfit)
```
```{r}
# predictions
Train_data$predicted.risk = predict(lgfit, newdata=Train_data, type="response")
table(Train_data$Class, as.numeric(Train_data$predicted.risk >= 0.5))
```
```{r}
# calculate ROC
library(ROCR)
pred = prediction(Train_data$predicted.risk, Train_data$Class)
as.numeric(performance(pred, "auc")@y.values)
```
```{r}
# plot curve
predict_Train = predict(lgfit, type="response")
ROCpred = prediction(predict_Train, Train_data$Class)
ROCperf = performance(ROCpred, "tpr", "fpr")
plot(ROCperf)
```

## Fraud detection
```{r}
data(GermanCredit)
FraudData<-GermanCredit[,1:10]
head(FraudData)
```
```{r}
# split data
len<-dim(FraudData)[1]
train<- sample(1:len , 0.8*len)
TrainData<-FraudData[train,]
TestData<-FraudData[-train,]
```
```{r}
# random forest
library(randomForest)
fraud_model <-randomForest(Class~.,data=TrainData, ntree=50, proximity=TRUE)
print(fraud_model)
```
```{r}
# plot model
plot(fraud_model)
```

```{r}
# importance of predictors
importance(fraud_model)
```
```{r}
# prediction
TestPred<-predict(fraud_model,newdata=TestData)
table(TestPred, TestData$Class)
```

## Liability management
