---
title: "Chapter 4 Time Series modeling"
output: word_document
---

```{r}
## Convert data to time series

StockPrice<-c(23.5,23.75,24.1,25.8,27.6,27,27.5,27.75,26,28,27,25.5)
StockPrice
```
```{r}
# use ts to create ts object
StockPricets<- ts(StockPrice,start = c(2016,1),frequency = 12)	
# StockPricets 
plot(StockPricets)
```
```{r}
# read external data
library(zoo)
# zoo can handle uneven time steps
StockData <- read.table("DataChap4.csv",header = TRUE, sep = ",", nrows=3)
dt <- as.Date(StockData$Date, format="%m/%d/%Y")
Stockdataz <- zoo(x=cbind(StockData$Volume,StockData$Adj.Close), order.by=dt) 
colnames(Stockdataz) <- c("Volume","Adj.Close")
Stockdataz
```
```{r}
# subsetting
StockData <- read.zoo("DataChap4.csv",header = TRUE, sep = ",",format="%m/%d/%Y")
window(StockData, start=as.Date("2016/11/1"), end=as.Date("2016/11/3"))
```
```{r}
# merging zoo objects
StockData <- read.table("DataChap4.csv",header = TRUE, sep = ",",nrows=3)
zVolume <-zoo(StockData[,2:2],as.Date(as.character(StockData[, 1]), format="%m/%d/%Y"))
zAdj.Close <-zoo(StockData[,3:3],as.Date(as.character(StockData[, 1]), format="%m/%d/%Y"))
cbind(zVolume, zAdj.Close)
plot(StockData$Adj.Close) # not same as in book
```
```{r message=FALSE}
# xts object
library(xts)
StockData <- read.zoo("DataChap4.csv",header = TRUE, sep = ",",format="%m/%d/%Y",nrows=3)
matrix_xts <- as.xts(StockData,dateFormat='POSIXct')
matrix_xts
str(matrix_xts)
```
```{r}
# construct xts from scratch
x<-matrix(5:8, ncol =2, nrow =2)
dt<-as.Date(c("2016-02-02","2016-03-02"))
xts_object<-xts(x,order.by=dt)
colnames(xts_object) <- c("a","b")
xts_object
```
```{r}
# linear Filters
StockData <- read.zoo("DataChap4.csv",header = TRUE, sep = ",",format="%m/%d/%Y")
PriceData<-ts(StockData$Adj.Close, frequency = 5)
plot(PriceData,type="l")
WeeklyMAPrice <- filter(PriceData,filter=rep(1/5,5))
monthlyMAPrice <- filter(PriceData,filter=rep(1/25,25))
lines(WeeklyMAPrice,col="red")
lines(monthlyMAPrice,col="blue")
```
```{r}
# AR
PriceData<-ts(StockData$Adj.Close, frequency = 5)
acf(PriceData, lag.max = 10)
```
```{r}
pacf(PriceData, lag.max = 10)
```
```{r}
# MA
library(astsa)
VolumeData<-ts(StockData$Volume, frequency = 5)
par(mfrow = c(2, 1))
acf(VolumeData, lag.max = 10)
pacf(VolumeData, lag.max = 10)
# acf2(StockData$Volume, lag.max = 10) # ???

```
```{r}
# Arima
PriceData<-ts(StockData$Adj.Close, frequency = 5)
plot(PriceData)
```
```{r}
# first order of differencing
PriceDiff <- diff(PriceData, differences=1)
plot(PriceDiff)
```
```{r}
# check ACF plot again on differeced data
par(mfrow = c(2, 1))
acf(PriceDiff, lag.max = 10)
pacf(PriceDiff, lag.max = 10)

# shows a possible ARIMA(0, 1, 1)
```
```{r}
# FIT A ARIMA MODEL
PriceArima <- arima(PriceData, order=c(0,1,1))
PriceArima
```
```{r message=FALSE}
# predict future trend
library(forecast)
FutureForecast<-forecast(PriceArima, h=5)
FutureForecast
```
```{r}
# plot predictions
plot(FutureForecast)
```
```{r}
# check residuals correlations
Box.test(FutureForecast$residuals, lag=20, type="Ljung-Box")

# p-value > 0.05, not significant correlations
```
```{r}
# GARCH
# install.packages("rugarch")
library(rugarch)
snp <- read.zoo("DataChap4SP500.csv",header = TRUE, sep = ",",format="%m/%d/%Y")
gspec.ru <- ugarchspec(mean.model=list( armaOrder=c(0,0)), distribution="std")
gfit.ru <- ugarchfit(gspec.ru, snp$Return)
coef(gfit.ru)
```
```{r}
# forecast
FutureForecast <- ugarchforecast(gfit.ru, n.ahead = 5)
FutureForecast
```
```{r}
# EGARCH
snp <- read.zoo("DataChap4SP500.csv",header = TRUE, sep = ",",format="%m/%d/%Y")
egarchsnp.spec <- ugarchspec(variance.model=list(model="eGARCH",garchOrder=c(1,1)),
                        mean.model=list(armaOrder=c(0,0)))
egarchsnp.fit <- ugarchfit(egarchsnp.spec, snp$Return)
egarchsnp.fit
coef(egarchsnp.fit)
```
```{r}
# forecast
FutureForecast <- ugarchforecast(egarchsnp.fit, n.ahead = 5)
FutureForecast

```
```{r}
# VGARCH
# install.packages("rmgarch")
# install.packages("PerformanceAnalytics")
library(rmgarch)
library(PerformanceAnalytics)
snpdji <- read.zoo("DataChap4SPDJIRet.csv",header = TRUE, sep = ",",format="%m/%d/%Y")

garch_spec <- ugarchspec(mean.model = list(armaOrder = c(2,1)),variance.model = list(garchOrder = c(1,1), model = "sGARCH"), distribution.model = "norm")

dcc.garch_spec <- dccspec(uspec = multispec( replicate(2, garch_spec) ), dccOrder = c(1,1), distribution = "mvnorm")
dcc_fit <- dccfit(dcc.garch_spec,data = snpdji)
fcst <- dccforecast(dcc_fit,n.ahead=5)
fcst
```
```{r}
# DCC
snpdji <- read.zoo("DataChap4SPDJIRet.csv",header = TRUE, sep = ",",format="%m/%d/%Y")
garchspec <- ugarchspec(mean.model = list(armaOrder = c(0,0)), 
                variance.model = list(garchOrder = c(1,1), 
                model = "sGARCH"), distribution.model = "norm")
 
dcc.garchsnpdji.spec <-  dccspec(uspec = multispec( replicate(2, garchspec) ), dccOrder = c(1,1), distribution = "mvnorm")

dcc_fit <- dccfit(dcc.garchsnpdji.spec , data = snpdji, fit.control=list(scale=TRUE))
dcc_fit

```


