---
title: "quantstrat tutorial"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Package setup : do not run if already done

* Codes from the following website :
https://statsmaths.github.io/stat395-f17/assets/final_project/amarnani.html

```{r message=FALSE, warning=FALSE}
if (!require("TTR")) {
  install.packages("TTR")
  library(TTR)
}
if (!require("quantstrat")) {
  if(!require("devtools")) {
    install.packages("devtools")
    require(devtools)
  }
  install_github("braverock/blotter") # dependency
  install_github("braverock/quantstrat")
}

if (!require("IKTrading")){
  install_github("IlyaKipnis/IKTrading", force=TRUE)
}
```
```{r}
library(devtools)
library(quantmod)
library(quantstrat)
library(TTR)
# library(png)
library(IKTrading)
```

## Part 1 Boiler plate
```{r}
rm(list = ls(.blotter), envir = .blotter)

initdate <- "2015-01-01"
from <- "2015-01-01" #start of backtest
to <- "2017-01-01" #end of backtest

Sys.setenv(TZ= "EST") #Set up environment for timestamps

currency("USD") #Set up environment for currency to be used
```
```{r message=FALSE, warning=FALSE}
symbols <- c("MSFT", "GOOG", "FB", "TWTR", "AMZN", "IBM") 
#symbols used in our backtest

getSymbols(Symbols = symbols, src = "yahoo", from=from) 
#receive data from google finance,  adjusted for splits/dividends
```
```{r}
tradesize <-10000 #default trade size
initeq <- 100000 #default initial equity in our portfolio

strategy.st <- portfolio.st <- account.st <- "firststrat" 
#naming strategy, portfolio and account

#removes old portfolio and strategy from environment
rm.strat(portfolio.st)
rm.strat(strategy.st) 

#initialize portfolio, account, orders and strategy objects
initPortf(portfolio.st, symbols = symbols, initDate = initdate, currency = "USD")
```
```{r}
initAcct(account.st, portfolios = portfolio.st, initDate = initdate, currency = "USD", initEq = initeq)
```
```{r}
initOrders(portfolio.st, initDate = initdate)
strategy(strategy.st, store=TRUE)
```

## Part 2: Indicators, Signals, Rules
```{r}
#Plots the 50, 200 day SMA
candleChart(IBM, up.col = "black", dn.col = "red", theme = "white")
addSMA(n = c(200,50), on = 1, col = c("red", "blue"))
```

```{r}
#Plots the RSI with lookback equal to 10 days 
plot(RSI(Cl(AMZN), n=10))
```

### Indicators
```{r}
add.indicator(strategy = strategy.st,
              name = 'SMA',
              arguments = list(x = quote(Cl(mktdata)), n=200),
              label = 'SMA200')
```

```{r}
add.indicator(strategy = strategy.st,
              name = 'SMA',
              arguments = list(x = quote(Cl(mktdata)), n=50),
              label = 'SMA50')
```
```{r}
add.indicator(strategy = strategy.st,
              name = 'RSI',
              arguments = list(price = quote(Cl(mktdata)), n=3),
              label = 'RSI_3')
```

### Signals

```{r}
#First Signal: sigComparison specifying when 50-day SMA above 200-day SMA
add.signal(strategy.st, name = 'sigComparison',
          arguments = list(columns=c("SMA50", "SMA200")),
          relationship = "gt",
          label = "longfilter")
```

```{r}
#Second Signal: sigCrossover specifying the first instance when 50-day SMA below 200-day SMA 
add.signal(strategy.st, name = "sigCrossover",
           arguments = list(columns=c("SMA50", "SMA200")),
           relationship = "lt",
           lablel = "sigCrossover.sig")
```

```{r}
#Third Signal: sigThreshold which specifies all instance when RSI is below 20 (indication of asset being oversold)
add.signal(strategy.st, name = "sigThreshold",
           arguments = list(column = "RSI_3", threshold = 20,
                            relationship = "lt", cross = FALSE),
           label = "longthreshold")
```

```{r}
#Fourth Signal: sigThreshold which specifies the first instance when rsi is above 80 (indication of asset being overbought)
add.signal(strategy.st, name = "sigThreshold",
           arguments = list(column = "RSI_3", threshold = 80,
                            relationship = "gt", cross = TRUE),
           label = "thresholdexit")
```

```{r}
#Fifth Signal: sigFormula which indicates that both longfilter and longthreshold must be true.
add.signal(strategy.st, name = "sigFormula",
           arguments = list(formula = "longfilter & longthreshold",
                            cross = TRUE),
          label = "longentry")
```

### Rules
```{r}
#The first rule will be an exit rule. This exit rule will execute when the market environment is no longer conducive to a trade (i.e. when the SMA-50 falls below SMA-200)
add.rule(strategy.st, name = "ruleSignal",
         arguments = list(sigcol = "sigCrossover.sig", sigval = TRUE,
                          orderqty = "all", ordertype = "market",
                          orderside = "long", replace = FALSE,
                          prefer = "Open"),
         type = "exit")
```

```{r}
#The second rule, similar to the first, executes when the RSI has crossed above 80. 
add.rule(strategy.st, name = "ruleSignal",
         arguments = list(sigcol = "thresholdexit", sigval = TRUE,
                          orderqty = "all", ordertype = "market",
                          orderside = "long", replace = FALSE,
                          prefer = "Open"),
         type = "exit")
```
```{r}
#Additionally, we also need an entry rule. This rule executes when longentry is true (or when long filter and longthreshold are true). That is when SMA-50 is above SMA-200 and the RSI is below 20.
add.rule(strategy.st, name = "ruleSignal",
         arguments = list(sigcol = "longentry", sigval = TRUE,
                          orderqty = 1, ordertype = "market",
                          orderside = "long", replace = FALSE,
                          prefer = "Open", osFUN = IKTrading::osMaxDollar,
                          tradeSize = tradesize, maxSize = tradesize),
         type = "enter")
```

## Part 3: Performance Analytics
To review, the following is essentially the strategy we have coded up thus far:

* Buy When: SMA-50 > SMA-200 AND the RSI < 20
* Sell When: SMA-50 < SMA-200 OR RSI > 80

```{r}
out <- applyStrategy(strategy = strategy.st, portfolios = portfolio.st)
updatePortf(portfolio.st)
daterange <- time(getPortfolio(portfolio.st)$summary)[-1]

updateAcct(account.st, daterange)
updateEndEq(account.st)
```
```{r}
for(symbol in symbols){
  
  chart.Posn(Portfolio = portfolio.st, Symbol = symbol, 
             TA= c("add_SMA(n=50, col='blue')", "add_SMA(n=200, col='red')"))
}
```

```{r}
tstats <- tradeStats(Portfolios = portfolio.st)

tstats[, 4:ncol(tstats)] <- round(tstats[, 4:ncol(tstats)],2)
print(data.frame(t(tstats[,-c(1,2)])))
```
    
```{r}
final_acct <- getAccount(account.st)
end_eq <- final_acct$summary$End.Eq

returns <- Return.calculate(end_eq, method="log")
charts.PerformanceSummary(returns, colorset = bluefocus, main = "Strategy Performance")
```
```{r}
returns_2 <- PortfReturns(account.st)
colnames(returns_2) <- symbols
returns_2 <- na.omit(cbind(returns_2,Return.calculate(end_eq)))
names(returns_2)[length(names(returns_2))] <- "Total"
returns_2 <- returns_2[,c("Total", symbols)]
round(tail(returns_2,5),6)

chart.CumReturns(returns_2, colorset = rich10equal, legend.loc = "topleft", main = "Strategy Cumulative Returns")
```
```{r}
chart.Boxplot(returns_2, main = "Strategy Returns", colorset = rich10equal)
```

