---
title: "Chapter 08 Forecasting"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## 8.1 Inroduction
```{r}
library(fpp2)
# white noise
set.seed(3)
wn <- ts(rnorm(36))
autoplot(wn)
```
```{r}
# ACF
ggAcf(wn) +
  ggtitle("Sample ACF for white noise")
```
```{r}
# pigs slaugtered
autoplot(pigs/1000) +
  xlab("year") +
  ylab("Thousands") +
  ggtitle("Monthly number of pigs slightered in Victoria")
```
```{r}
# ACF
ggAcf(pigs) +
  ggtitle("ACF of pigs sloughtered")
```
```{r}
# Ljung-Box test
# a small p-value indicates the data are probably not white noise !
Box.test(pigs, lag = 24, fitdf = 0, type = "Lj")
```
```{r}
# p-value large, so white noise ?
Box.test(wn, type = "Lj")
```

## 8.2 Forecasts and potenital futures
```{r}
fc <- naive(oil)
autoplot(oil, series = "Data") +
  xlab("year") +
  autolayer(fitted(fc), series = "Fitted") +
  ggtitle("Oil production in Saudi")
  
```
```{r}
# residuals
autoplot(residuals(fc))
```
```{r}
# check residuals
checkresiduals(fc)
```

```{r}
# training and test sets
training <- window(oil, end = 2003)
test <- window(oil, start = 2004)
fc <- naive(training, h = 10)
autoplot(fc) +
  autolayer(test, series = "test data")
```

```{r}
# check the type of data
class(training)
```
```{r}
# accuracy
accuracy(fc, test)
```

```{r}
# cross-validation
e <- tsCV(oil, forecastfunction = naive, h = 1)
mean(e^2, na.rm = TRUE)
```
```{r}
# self defined func
sq <- function(u){u^2}
for(h in 1:10){
  oil %>% 
    tsCV(forecastfunction = naive, h = h) %>% 
    sq() %>% 
    mean(na.rm = TRUE) %>% 
    print()
}
```

## 8.3 Exponentially weighted forecasts
```{r}
# simple exponential smoothing
oildata <- window(oil, start = 1996)
fc <- ses(oildata, h = 5)
summary(fc)
```
```{r}
autoplot(fc) +
  ylab("oil - millions of tonnes") +
  xlab("year")
```

```{r}
# exponential smoothing with trend
AirPassengers %>% 
  holt(h = 5) %>% 
  autoplot()
```
```{r}
# damped trend method
fc1 <- holt(AirPassengers, h = 15, PI = FALSE)
fc2 <- holt(AirPassengers, damped = TRUE, h = 15, PI = TRUE)
autoplot(AirPassengers) +
  xlab("year") +
  ylab("millions") +
  autolayer(fc1, series = "linear trend") +
  autolayer(fc2, series = "Damped trend")
```
```{r}
# exponential smoothing with trend and seasonal pattern
aust <- window(austourists, start = 2005)
fc1 <- hw(aust, seasonal = "additive")
fc2 <- hw(aust, seasonal = "multiplicative")
autoplot(aust) +
  xlab("year") +
  ylab("millions") +
  autolayer(fc1, series = "HW additive") +
  autolayer(fc2, series = "HW multiply")
```

```{r}
# state space models for exponential smoothing
# ETS models
ets(ausair)
```

```{r}
# air traffic
ausair %>%
  ets() %>% 
  forecast() %>% 
  autoplot()
```
```{r}
# monthly drug sales
ets(h02)
```

```{r}
h02 %>% 
  ets() %>% 
  forecast() %>% 
  autoplot()
```

## 8.4 Transformations for variance stabilization
```{r}
library(fpp2)
autoplot(usmelec) +
  xlab("year") +
  ylab("") +
  ggtitle("US monthly net electricity generation")
```

```{r}
autoplot(usmelec^0.5) +
  xlab("year") +
  ylab("") +
  ggtitle("Square root electricity generation")
```

```{r}
autoplot(log(usmelec)) +
  xlab("year") +
  ylab("") +
  ggtitle("log electricity generation")
```

```{r}
autoplot(-1/usmelec) +
  xlab("year") +
  ylab("") +
  ggtitle("inverse electricity generation")
```

```{r}
# box-cox transformation
BoxCox.lambda(usmelec)
```

```{r}
# back-transformation
usmelec %>% 
  ets(lambda =  -0.57) %>% 
  forecast(h = 60) %>% 
  autoplot()
```

```{r}
# ARIMA MODELS
autoplot(usnetelec) +
  xlab("year") +
  ylab("billion kwh") +
  ggtitle("US net electricity generation")
```

```{r}
# auto.arima
fit <- auto.arima(usnetelec)
summary(fit)
```
```{r}
# forecast
fit %>% forecast() %>% autoplot()
```

```{r}
# seasonal ARIMA
# monthly debit cards usage

autoplot(debitcards) +
  xlab("year") +
  ylab("million ISK") +
  ggtitle("retail debit card usage")
```
```{r}
# fit seasonal model
fit <- auto.arima(debitcards, lambda = 0)
fit
```

```{r}
# forecast
fit %>% 
  forecast(h = 36) %>% 
  autoplot() +
  xlab("year")
```

## 8.5 Dynamic regression
```{r}
# error term is an 'arima' process
# in regular regression, error term is 'white noise'

# us personal consumption and income
autoplot(uschange[, 1:2], facets = TRUE) +
  xlab("year") +
  ylab("") +
  ggtitle("Quarterly changes in consumption and personal income")
```

```{r}
# scatter plot
ggplot(aes(x = Income, y = Consumption),
       data = as.data.frame(uschange)) +
  geom_point()+
  ggtitle("Quarterly change in consumption and personal income")
```

```{r}
# dynamic regression model
fit <- auto.arima(uschange[, "Consumption"],
                  xreg = uschange[, "Income"])
fit
```
```{r}
# check residuals
checkresiduals(fit)
```

```{r}
# forecast
fcast <- forecast(fit, xreg = rep(0.8, 8))

autoplot(fcast) +
  xlab("year") +
  ylab("percentage change")
```

```{r}
# dynamic harmonic regression
# cafe expenditure
cafe <- window(auscafe, start = 2002)
fit <- auto.arima(cafe, xreg = fourier(cafe, K = 1),
                  seasonal = FALSE, lambda = 0)

fit %>% forecast(xreg = fourier(cafe, K = 1, h = 24)) %>% 
  autoplot() +
  ylim(1.6, 5.1)
```
```{r}
# K = 2
fit <- auto.arima(cafe, xreg = fourier(cafe, K = 2),
                  seasonal = FALSE, lambda = 0)

fit %>% forecast(xreg = fourier(cafe, K = 2, h = 24)) %>% 
  autoplot() +
  ylim(1.6, 5.1)
```

```{r}
# K = 3, 4, 5, 6
fit <- auto.arima(cafe, xreg = fourier(cafe, K = 3),
                  seasonal = FALSE, lambda = 0)

fit %>% forecast(xreg = fourier(cafe, K = 3, h = 24)) %>% 
  autoplot() +
  ylim(1.6, 5.1)
```



