---
title: "Import finanical data"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r message=FALSE}
library(TTR)
library(xts)
library(quantmod)
library(fpp2)
# not working anymore
# library(quantstrat)
# library(blotter)

```
## Quantmod
```{r}
getSymbols(Symbols = "AAPL", src = "yahoo")
getSymbols("AAPL")
```
```{r}
head(AAPL)
```
```{r}
# ts.plot(AAPL$AAPL.Close)
```
```{r}
str(AAPL)
```
```{r}
autoplot(AAPL$AAPL.Close)
```


## Quandl
```{r}
library(Quandl)
```
```{r}
quantmod::getSymbols(Symbols = "DGS10", src = "FRED")
```
```{r}
dgs10 <- Quandl::Quandl(code = "FRED/DGS10")
```
```{r}
dgs10 <- Quandl::Quandl(code = "FRED/DGS10", type = "xts")
# ts.plot(dgs10)
```
```{r}
autoplot(dgs10)
```

## Finding data from internet sources
* Yahoo finance
* google finance
* Oanda
* FRED

## Extracting columns from financial time series

```{r}
head(AAPL)
```
```{r}
apple_open <- Op(AAPL)
head(apple_open)
```
```{r}
apple_high <- Hi(AAPL)
head(apple_high)
```

```{r}
apple_ohlc <- OHLC(AAPL)
head(apple_ohlc)
```
```{r}
autoplot(apple_ohlc)
```

## Transforming multiple instruments
```{r}
data_env <- new.env()
getSymbols(c("SPY", "GE"), env = data_env, auto.assign = TRUE)
```
```{r}
head(data_env$GE)
```
```{r}
autoplot(Cl(data_env$GE))
```


```{r}
# use lapply
adjusted_list <- lapply(data_env, Ad)
# adjusted <- do.all(merge, adjusted_list)
```
## setting default arguments for getSymbols
```{r}
getSymbols("GDP", src = "FRED")
```
```{r}
autoplot(GDP)
```
```{r}
# getSymbols.FRED("GDP")
```
```{r}
gdp <- getSymbols("GDP", src = "FRED", auto.assign = FALSE)
str(gdp)
```
```{r}
getSymbols("NKE", from = "2019-01-01", src = "yahoo")
```
```{r}
autoplot(Cl(NKE))
```

## set per-instrument default arguments
```{r}
aapl <- getSymbols("AAPL", auto.assign = FALSE, src = "yahoo")
str(aapl)
```
## import invalid names
```{r}
getSymbols("^GSPC")
```
```{r}
head(GSPC)
```
```{r}
getSymbols("000001.SS", auto.assign = TRUE)
```
```{r}
head(`000001.SS`, n = 3)
```

```{r}
head(get("000001.SS"), n = 3)
```
```{r}
sse <- getSymbols("000001.SS", auto.assign = FALSE)
colnames(sse) <- paste("SSE", c("Open", "High", "Low", "Close", "Volume",
                                "Adjusted"), sep = ".")
```
```{r}
head(sse, n = 3)
```
## multiple instruments

```{r}
setSymbolLookup(SSE = list(name = "000001.SS"),
                FORD = list(name = "F"))
getSymbols(c("SSE", "FORD"))
```
```{r}
autoplot(Cl(FORD))
```
## making irregular data regular
```{r}
# regular data time squences
from_date <- as.Date("2017-01-01")
to_date <- as.Date("2017-01-03")
date_seq <- seq(from = from_date,
                to = to_date,
                by = "day")
```
```{r}
regular_xts <- xts(seq_along(date_seq), order.by = date_seq)
start(regular_xts)
```

## 4.5 Importing text files
```{r}
getSymbols("GE", src = "csv", dir = "~/DataAnalysis_H/Examples_R/QuantR/Data/Stocks")
```
```{r}
head(GE, 3)
```
```{r}
# use zoo format
ge_zoo <- read.zoo("~/DataAnalysis_H/Examples_R/QuantR/Data/Stocks/GE.csv",
                   sep = ",", header = TRUE)
```
```{r}
head(ge_zoo)
```
```{r}
plot(ge_zoo$Close, main = "in the past year")
```

```{r}
# any missing values
sum(is.na(ge_zoo))
```

