---
title: "Chapter 12 Bond valuation and analysis"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 12.1 Bond valuation
```{r}
# pv
pv <- 100

# rate
r <- 0.1

fv1 <- pv * (1 + r)

fv2 <- pv * (1 + r) * (1 + r)
```

```{r}
# present value or pv1
pv1 <- fv1 / (1 + r)
pv2 <- fv2 / ((1 + r) * (1 + r))
```

```{r}
# bond's cash flows
cf <- c(5, 5, 5, 5, 105)
cf <- data.frame(cf)
cf
```

```{r}
# discouting bond cf with a known yield
cf$t <- as.numeric(rownames(cf))

cf$pv_factor <- 1 / (1 + 0.06)^cf$t

cf$pv <- cf$cf * cf$pv_factor

# bond price
sum(cf$pv)
```

```{r}
# write a func
bondprc <- function(p, r, ttm, y){
  cf <- c(rep(p * r, ttm - 1), p * (1 + r))
  cf <- data.frame(cf)
  cf$t <- as.numeric(rownames(cf))
  cf$pv_factor <- 1 / (1 + y)^cf$t
  cf$pv <- cf$cf * cf$pv_factor
  sum(cf$pv)
}

# bond value
bondprc(100, 0.05, 5, 0.06)
```

## 12.2 price and yield relationship
```{r}
# yield on Moody's Baa index
library(Quandl)

baa <- Quandl("FED/RIMLPBAAR_N_M")

# subsetting
baa_yield <- subset(baa, baa$Date == "2016-09-30")

baa_yield <- baa_yield$Value / 100

baa_yield
```

```{r}
# value 5% bond using Baa yield
bondprc(p = 100, r = 0.05, ttm = 5, y = 0.0431)
```
```{r}
# price vs yield
prc_yld <- seq(0.02, 0.4, by = 0.01)

# to df
prc_yld <- data.frame(prc_yld)

# calculate price with different yields
for(i in 1:nrow(prc_yld)){
  prc_yld$price[i] <- bondprc(100, 0.10, 20, prc_yld$prc_yld[i])
}

# plot
plot(prc_yld, type = "l", col = "blue", main = "price vs yield")

```

```{r}
# us treasury yields
library(quantmod)
t10yr <- getSymbols(Symbols = "DGS10", src = "FRED", auto.assign = FALSE)

# sebsetting
t10yr <- t10yr["2006-01/2016-09"]

#plot
plot(x = index(t10yr),
     y = t10yr$DGS10,
     xlab = "Date",
     ylab = "Yield",
     type = "l",
     col = "red",
     main = "10 year yield")
```

```{r}
# find a bond's yield
# guess using 5% yield
bondprc(p = 100, r = 0.05, ttm = 5, y = 0.05)

bondprc(p = 100, r = 0.05, ttm = 5, y = 0.07)

bondprc(p = 100, r = 0.05, ttm = 5, y = 0.06)
```
```{r}
# uniroot to find YTM
# cash flow
cf <- c(-95.79, 5, 5, 5, 5, 105)

# bond valuation function
bval <- function(i, cf,
                 t = seq(along = cf))
                 sum(cf / (1 + i)^t)

# ytm function with uniroot
ytm <- function(cf){
  uniroot(bval, c(0, 1), cf = cf)$root
}

# use ytm() to get yield
ytm(cf)
```

## 12.3 Bond price volatility and price value of a basis point
```{r}
# small change, symmetric effect
bondprc(100, 0.1, 20, 0.101) / bondprc(100, 0.1, 20, 0.10) - 1
bondprc(100, 0.1, 20, 0.099) / bondprc(100, 0.1, 20, 0.10) - 1
```
```{r}
# large change, asymmetric effect
bondprc(100, 0.1, 20, 0.14) / bondprc(100, 0.1, 20, 0.10) - 1
bondprc(100, 0.1, 20, 0.06) / bondprc(100, 0.1, 20, 0.10) - 1
```

```{r}
# lower coupon, more volatile
bondprc(100, 0.1, 20, 0.08) / bondprc(100, 0.1, 20, 0.10) - 1
bondprc(100, 0.05, 20, 0.08) / bondprc(100, 0.05, 20, 0.10) - 1
bondprc(100, 0.00, 20, 0.08) / bondprc(100, 0.00, 20, 0.10) - 1
```

```{r}
# shorter maturity, more volatile
bondprc(100, 0.1, 20, 0.08) / bondprc(100, 0.1, 20, 0.10) - 1
bondprc(100, 0.1, 10, 0.08) / bondprc(100, 0.1, 10, 0.10) - 1
bondprc(100, 0.1, 5, 0.08) / bondprc(100, 0.1, 5, 0.10) - 1
```

```{r}
# dollar value of an 01 = bond price votatility
bondprc(100, 0.05, 20, 0.05)
bondprc(100, 0.05, 20, 0.0501)
abs(bondprc(100, 0.05, 20, 0.05) - bondprc(100, 0.05, 20, 0.0501))
```

```{r}
# duration
p <- bondprc(100, 0.05, 10, 0.04)
p_down <- bondprc(100, 0.05, 10, 0.03)
p_up <- bondprc(100, 0.05, 10, 0.05)
duration <- (p_down -  p_up)/(2 * p * 0.01)
duration_pct_change <- -duration * 0.01
duration_dollar_change <- duration_pct_change * p
duration_dollar_change
```

```{r}
# convexity
convexity <- (p_down +  p_up - 2 * p)/(p * (0.01^2))
convexity_pct_change <- 0.5 * convexity * 0.01^2
convexity_dollar_change <- 0.5 * convexity * 0.01^2 * p
```

```{r}
# effect of duration + convexity
duration_dollar_change + convexity_dollar_change
```

```{r}
# current price
p

# estimated price
duration_dollar_change + convexity_dollar_change + p
```

## 12.4 an complete example
```{r}
# load lib
library(Quandl)
```
```{r}
# moody's Aaa yield
aaa <- Quandl("FED/RIMLPAAAR_N_M")

# subsetting
aaa_yield <- subset(aaa, aaa$Date == "2016-09-30")

aaa_yield <- as.numeric(aaa_yield$Value) / 100
aaa_yield
```
```{r}
# bond valuation

# cash flow
cf <- c(3, 3, 3, 3, 3, 3, 3, 103)
cf <- data.frame(cf)

# add time
cf$t <- seq(1, 8, 1)

# PV factor
cf$pv_factor <- 1/(1 + aaa_yield)^cf$t

# PV
cf$pv <- cf$cf * cf$pv_factor

# price bond
sum(cf$pv)
```

```{r}
# alternative cash flow vector 
alt_cf <- function(r, p, ttm){
  c(rep(p * r, ttm - 1), p * (1 + r))
}

# generate vector
alt_cf(r = 0.03, p = 100, ttm = 8)
```
```{r}
# calculate duration
px <-  bondprc(p = 100, r = 0.03, ttm = 8, y = 0.0341)

# bond price, yield increases
px_up <- bondprc(p = 100, r = 0.03, ttm = 8, y = 0.0441)

# bond price,  yield decreases
px_down <- bondprc(p = 100, r = 0.03, ttm = 8, y = 0.0241)

# duration
duration <- (px_down - px_up) / (2 * px * 0.01)

# percentage
duration_pct_change <- -duration / 100
duration_pct_change

# dollar effect
duration_dollar_change <- -px * duration * 0.01
duration_dollar_change
```

```{r}
# convexity measure
convexity <- (px_up + px_down - 2 * px)/(px * 0.01^2)

# percentage effect
convexity_pct_change <- 0.5 * convexity * (0.01)^2

# dollar effect
convexity_dollar_change <- convexity_pct_change * px
convexity_dollar_change
```

```{r}
# price change using duration and convexity
price_change <- duration_dollar_change + convexity_dollar_change
price_change

# new price
new_price <- px + duration_dollar_change + convexity_dollar_change
new_price
```

