---
title: "Chapter 05 Introduction to time series analysis"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## 5.1 Examples
```{r}
head(sunspots)
```
```{r}
# coredata(sunspots)
# index(sunspots)
plot(sunspots)
```
```{r}
# sampling frequency : R function
start(sunspots)
```
```{r}
end(sunspots)
```
```{r}
frequency(sunspots)
```
```{r}
deltat(sunspots)
```
```{r}
# building ts objects
data_vector <- c(10, 6, 11, 8, 10, 3, 6, 9)
time_series <- ts(data_vector)
plot(time_series)
```
```{r}
# more with start date
time_series <- ts(data_vector, start = 2001, frequency = 1)
plot(time_series)
```
```{r}
is.ts(data_vector)
```
## 5.2 predicting the future
```{r}
dz <- diff(sunspots)
ts.plot(dz)
```
```{r}
ts.plot(diff(sunspots, lag = 50))
```
```{r}
# while noise
white_noise <- arima.sim(model = list(order = c(0,0,0)), n = 100)
ts.plot(white_noise)
```
```{r}
# white noise with more parameters
white_noise_2 <- arima.sim(model = list(order = c(0,0,0)), n = 100,
                         mean = 100, sd = 10)
ts.plot(white_noise_2)
```
```{r}
mean(white_noise_2)
```
```{r}
var(white_noise_2)
```
```{r}
# check on the white noise 2
arima(white_noise_2, order = c(0,0,0))
```
```{r}
# random walk
random_walk <- arima.sim(model = list(order = c(0,1,0)), n = 100)
ts.plot(random_walk)
```
```{r}
# difference series
random_walk_diff <- diff(random_walk)
ts.plot(random_walk_diff)
```
```{r}
# random walk with a drift
rw_drift <- arima.sim(model = list(order = c(0,1,0)), 
                      n = 100, mean = 1)
ts.plot(rw_drift)
```
```{r}
# difference again
rw_drift_diff <- diff(rw_drift)
ts.plot(rw_drift_diff)
```
```{r}
# estimate the random work model
rw_diff <- diff(random_walk)
ts.plot(rw_diff)
```
```{r}
# fit rw model to the differenced data
model_wn <- arima(rw_diff, order = c(0,0,0))

# store intercept
int_wn <- model_wn$coef

ts.plot(random_walk)
abline(0, int_wn)
```
```{r}
# white noise or random walk - stationary
while_noise <- arima.sim(model = list(order = c(0,0,0)), n = 100)
random_walk <- cumsum(white_noise)
wn_drift <- arima.sim(model = list(order=c(0,0,0)), n = 100, mean = 0.4)
rw_drfit <- cumsum(wn_drift)
plot.ts(cbind(white_noise, random_walk, wn_drift, rw_drfit))
```

## 5.3 Correlation and plotting
```{r}
data("EuStockMarkets")
eu_stocks <- EuStockMarkets
plot(eu_stocks)
```

```{r}
# return
returns <- eu_stocks[-1, ]/eu_stocks[-1360, ] -1

# to ts
returns <- ts(returns, start = c(1991, 130), frequency = 260)

# plot returns
plot(returns)
```

```{r}
# log returns
logreturns <- diff(log(eu_stocks))
plot(logreturns)
```

```{r}
# percent returns
eu_percentreturns <- returns*100

colMeans(eu_percentreturns)
```
```{r}
# sample variance
apply(eu_percentreturns, MARGIN = 2, FUN = var)
```
```{r}
# standard deviation
apply(eu_percentreturns, 2, sd)
```
```{r}
# plot histograms
par(mfrow = c(2, 2))
apply(eu_percentreturns, 2, hist, main = "", xlab = "Percentage Return")
```

```{r}
# plot histograms
par(mfrow = c(2, 2))
apply(eu_percentreturns, 2, qqnorm, main = "")
qqline(eu_percentreturns)
```
```{r}
pairs(logreturns)
```
```{r}
# covariance
cov(logreturns)
```
```{r}
# correlations
cor(logreturns)
```
```{r}
x <- eu_stocks[, "DAX"]
x_t0 <- lag(x, n =10)
plot(x, x_t0)
```
```{r}
acf(x, lag.max = 1)
```
```{r}
n = length(x)
cor(x, x_t0) * (n - 1)/n
```

## 5.4 autoregressive model
```{r}
# inflation data
data(Mishkin, package = "Ecdat")
inflation <- as.ts(Mishkin[, 1])
ts.plot(inflation)
```
```{r}
acf(inflation)
```
```{r}
# AR model
AR_inflation <- arima(inflation, order = c(1, 0, 0))
print(AR_inflation)
```
```{r}
# fitted values
ts.plot(inflation)

AR_inflation_fitted <- inflation - residuals(AR_inflation)

points(AR_inflation_fitted, type = "l", col = "red", lty = 2)
```
```{r}
# forcasting
predict(AR_inflation)
```
```{r}
# h - steps
predict(AR_inflation, n.ahead = 6)
```

## 5.5 Moving average model
```{r}
inflation_changes <- diff(inflation)
par(mfrow = c(2, 1))
ts.plot(inflation, xlab = "")
ts.plot(inflation_changes, xlab = "")
```
```{r}
acf(inflation_changes, lag.max = 24)
```
```{r}
# MA processes
MA_inflation_changes <- arima(inflation_changes, order = c(0, 0, 1)) 
print(MA_inflation_changes)
```

```{r}
# MA, fitted values
ts.plot(inflation_changes)
MA_inflation_changes_fitted <- inflation_changes - residuals(MA_inflation_changes)

points(MA_inflation_changes_fitted, type = "l", col= "red", lty = 2)
```
```{r}
# Forecasting
predict(MA_inflation_changes, n.ahead = 6)
```

```{r}
# compare AR and MA models
AIC(MA_inflation_changes)
BIC(MA_inflation_changes)
```
```{r}
AR_inflation_changes <- arima(inflation_changes, order = c(1, 0, 0)) 
AIC(AR_inflation_changes)
BIC(AR_inflation_changes)
```

