---
title: "Chapter 09 Visualizing time series"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 9.1 plot functions
```{r}
library(fpp2)
plot(uschange[, 1], main = "consumption")
lines(uschange[, 1], col = "red", lwd = 2)
```
```{r}
# subtitle
plot(uschange[, 1], main = "consumption", sub = "in US")
lines(uschange[, 1], col = "red", lwd = 2)
```
```{r}
# plot two trend in one 
plot(uschange[, 1], main = "consumption")
lines(uschange[, 2], col = "red")
```

```{r}
# display units for the second trend
plot(uschange[, 1], main = "consumption")
lines(uschange[, 2], col = "red")
axis(side = 4, at = pretty(uschange[, 2]))
```
```{r}
# put legends for trends
plot(uschange[, 1], main = "consumption")
lines(uschange[, 2], col = "red")
axis(side = 4, at = pretty(uschange[, 2]))
legend(x = "bottom", legend = c("Stock X", "Stock Y"),
       col = c("black", "red"), lty = c(1, 1))
abline(h = 0)
```

```{r}
# add vertical line
plot(uschange[, 1], main = "consumption")
lines(uschange[, 1], col = "red", lwd = 2)
abline(v = as.Date("2000/Q1")) # not working
```
```{r}
# use chart.TimeSeries from 'PerformanceAnalytics'
library(PerformanceAnalytics)
chart.TimeSeries(uschange[, 1], main = "another try")
```

## 9.2 univariate time series analysis
```{r}
library(quantmod)
library(TTR)
getSymbols("GE", src = "yahoo")
```

```{r}
# plot GE stocks
plot(GE$GE.Close, main = "GE stock price")
```
```{r}
# returns
rtn <- ROC(GE$GE.Close)
plot(rtn, main = "GE stock returns")
```

```{r}
# histogram
hist(rtn,
     breaks = 30,
     main = "GE return distribution",
     probability = TRUE,
     xlab = "")
```

```{r}
# boxplot
boxplot(coredata(rtn), horizontal = TRUE, main = "GE return distribution")
```

```{r}
# autocorrelation
acf(na.omit(rtn), lag.max = 10, main = "GE return autocorrelation")
```

```{r}

# qq norm plot
qqnorm(na.omit(rtn), main = "GE return QQ-Plot")
qqline(rtn, col = "red")
```

## 9.3 mutiple time series
```{r}
# get boeing stock
getSymbols("BA", src = "yahoo")
getSymbols("MSFT", src = "yahoo")

```

```{r}
# stacked barplot
barplot(GE$GE.Close, BA$BA.Close, beside = TRUE)
```

```{r}
# scatter plot
plot(x = coredata(GE$GE.Close), y = coredata(BA$BA.Close))
```
```{r}
# merge GE and BA
my_data <- merge(GE$GE.Close, BA$BA.Close, MSFT$MSFT.Close)
head(my_data)
```
```{r}
# pairs
cor(my_data)
```
```{r}
# pairs
pairs(coredata(my_data))
```
```{r}
# plot multiple time series
plot.xts(my_data)
```

## 9.4 case study

