---
title: "Chapter 02 Networking Part I"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Yahoo! Finance API
### Setting Up Directories
```{r}
library(quantmod)
```

```{r}
rootdir <- "~/Platform/"
datadir <- "~/Platform/stockdata/"
functiondir <- "~/Platform/functions/"
```
### URL Query Building
```{r}
yahoo <- function(sym, current = TRUE,
                  a = 0, b = 1, c = 2000, d, e, f,
                  g = "d")
{

  if(current){
    f <- as.numeric(substr(as.character(Sys.time()), start = 1, stop = 4))
    d <- as.numeric(substr(as.character(Sys.time()), start = 6, stop = 7)) - 1
    e <- as.numeric(substr(as.character(Sys.time()), start = 9, stop = 10))
  }
  
  require(quantmod)

  tryCatch(
  suppressWarnings(
  sym <- getSymbols(Symbols = sym)
  ))
}

setwd(functiondir)
dump(list = c("yahoo"), "yahoo.R")
```
```{r}
GE <- yahoo("GE")
```

### Data Acquisition
```{r}
# Up-to-date at time of writing (May 2016)
url <- "http://trading.chrisconlan.com/SPstocks.csv"
S <- as.character(read.csv(url, header = FALSE)[,1])
```
```{r}
setwd(rootdir)
dump(list = "S", "S.R")
```
#### Listing 2-4. Initial Directory Loader
```{r message=FALSE}
# Load "invalid.R" file if available 
invalid <- character(0)
setwd(rootdir)
if("invalid.R" %in% list.files()) source("invalid.R")


# Find all symbols not in directory and not missing
setwd(datadir)
toload <- setdiff(S[!paste0(S, ".csv") %in% list.files()], invalid)

# Fetch symbols with yahoo function, save as .csv or missing
source(paste0(functiondir, "yahoo.R"))
if(length(toload) != 0){
  for(i in 1:length(toload)){
    
  df <- yahoo(toload[i])
  
  if(!is.null(df)) {
    write.csv(df[nrow(df):1], file = paste0(toload[i], ".csv"),
              row.names = FALSE) 
  } else {
    invalid <- c(invalid, toload[i])
  }
    
}
}

setwd(rootdir)
dump(list = c("invalid"), "invalid.R")
```
```{r}
# Clears R environment except for path variables and functions
rm(list = setdiff( ls(), c("rootdir", "functiondir", "datadir", "yahoo")))
gc()
```

### Loading Data into Memory
```{r}
SPY <- getSymbols( c("SPY"), from = "2012-01-01", auto.assign = FALSE)
```

